name: terraform-cicd
on:
    push:
        branches:
            - main
# jobs:
#     terraform:
#         runs-on: ubuntu-latest
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.MY_AWS_KEY }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.MY_AWS_ACCESS_KEY }}
#           AWS_DEFAULT_REGION: "us-east-1"
    
#         services:
#           terraform:
#             image: registry.gitlab.com/gitlab-org/gitlab-build-images:terraform
#             entrypoint:
#               - '/usr/bin/env'
#               - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
#         steps:
#           - name: Checkout Repository
#             uses: actions/checkout@v2
    
#           - name: Setup Terraform
#             run: |
#               terraform --version
#               terraform init -backend-config="tfstate.config"
#       validate:
#         needs: terraform
#         runs-on: ubuntu-latest
    
#         steps:
#           - name: Checkout Repository
#             uses: actions/checkout@v2
    
#           - name: Validate Terraform
#             run: terraform validate
#       plan:
#         needs: validate
#         runs-on: ubuntu-latest
    
#         steps:
#           - name: Checkout Repository
#             uses: actions/checkout@v2
    
#           - name: Apply Terraform Plan
#             run: terraform plan -out="planfile"
    
#       apply:
#         needs: plan
#         runs-on: ubuntu-latest
    
#         steps:
#           - name: Checkout Repository
#             uses: actions/checkout@v2
    
#           - name: Apply Terraform
#             run: terraform apply -input=false "planfile"
    
#           - name: Cleanup Plan File
#             run: rm planfile
    
#         # Trigger this job manually
#         manual:
#           job: apply
    
#       destroy:
#         needs: apply
#         runs-on: ubuntu-latest
    
#         steps:
#           - name: Checkout Repository
#             uses: actions/checkout@v2
    
#           - name: Destroy Terraform Resources
#             run: terraform destroy --auto-approve
    
#         # Trigger this job manually
#         manual:
#           job: destroy
